version: "3.9"
services:
  ssh:
    build: "."
    image: mqttproxy
    ports:
      - "2022:22"
    environment:
      INTERVAL: 30
      BAN_ATTEMPTS: 5
      BAN_TIME: 12h
      BAN_FIND_INTERVAL: 10m
    cap_add:
      - NET_ADMIN
    volumes:
      - "./keys/:/opt/keys/"
      - "./ag/work/:/opt/adguardhome/work/"
      - "./ag/conf/:/opt/adguardhome/conf/"
