version: "3.9"
services:
  ssh:
    build: "."
    ports:
      - "22:22"
    environment:
      INTERVAL: 30
#      BAN_ATTEMPTS: 1
#      BAN_TIME: 1m
    cap_add:
      - NET_ADMIN
    volumes:
      - "./keys/:/opt/keys/"

